-- Lab schemas for ORDS MCP multi-pool demo.
-- Executed by gvenzl/oracle-free as SYS on first volume init (FREEPDB1).
-- At work: one MCP pool per real database; same role-gating pattern.

WHENEVER SQLERROR EXIT SQL.SQLCODE

ALTER SESSION SET CONTAINER = FREEPDB1;

DECLARE
  PROCEDURE drop_user_if_exists(p_name VARCHAR2) IS
    c NUMBER;
  BEGIN
    SELECT COUNT(*) INTO c FROM dba_users WHERE username = UPPER(p_name);
    IF c > 0 THEN
      EXECUTE IMMEDIATE 'DROP USER ' || UPPER(p_name) || ' CASCADE';
    END IF;
  END;
BEGIN
  drop_user_if_exists('HR');
  drop_user_if_exists('FIN');
  drop_user_if_exists('HR_MCP_RO');
  drop_user_if_exists('FIN_MCP_RO');
END;
/

CREATE USER hr IDENTIFIED BY "HrApp_ChangeMe1"
  DEFAULT TABLESPACE users QUOTA UNLIMITED ON users;
GRANT CREATE SESSION, CREATE TABLE TO hr;

CREATE USER fin IDENTIFIED BY "FinApp_ChangeMe1"
  DEFAULT TABLESPACE users QUOTA UNLIMITED ON users;
GRANT CREATE SESSION, CREATE TABLE TO fin;

CREATE USER hr_mcp_ro IDENTIFIED BY "HrMcp_ChangeMe1"
  DEFAULT TABLESPACE users QUOTA UNLIMITED ON users;
GRANT CREATE SESSION, CREATE TABLE, CREATE SYNONYM, CREATE VIEW TO hr_mcp_ro;

CREATE USER fin_mcp_ro IDENTIFIED BY "FinMcp_ChangeMe1"
  DEFAULT TABLESPACE users QUOTA UNLIMITED ON users;
GRANT CREATE SESSION, CREATE TABLE, CREATE SYNONYM, CREATE VIEW TO fin_mcp_ro;

-- HR objects (as HR)
ALTER SESSION SET CURRENT_SCHEMA = hr;

CREATE TABLE employees (
  employee_id   NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  first_name    VARCHAR2(50) NOT NULL,
  last_name     VARCHAR2(50) NOT NULL,
  department    VARCHAR2(50),
  email         VARCHAR2(100)
);

INSERT INTO employees (first_name, last_name, department, email)
  VALUES ('Ada', 'Lovelace', 'Engineering', 'ada@example.com');
INSERT INTO employees (first_name, last_name, department, email)
  VALUES ('Grace', 'Hopper', 'Engineering', 'grace@example.com');
INSERT INTO employees (first_name, last_name, department, email)
  VALUES ('Alan', 'Turing', 'Research', 'alan@example.com');
COMMIT;

GRANT SELECT ON hr.employees TO hr_mcp_ro;

-- FIN objects
ALTER SESSION SET CURRENT_SCHEMA = fin;

CREATE TABLE invoices (
  invoice_id    NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  vendor_name   VARCHAR2(100) NOT NULL,
  amount_usd    NUMBER(12,2) NOT NULL,
  status        VARCHAR2(20) DEFAULT 'OPEN'
);

INSERT INTO invoices (vendor_name, amount_usd, status)
  VALUES ('Acme Cloud', 1200.00, 'OPEN');
INSERT INTO invoices (vendor_name, amount_usd, status)
  VALUES ('Office Supplies Co', 84.50, 'PAID');
INSERT INTO invoices (vendor_name, amount_usd, status)
  VALUES ('SecureLink ISP', 499.00, 'OPEN');
COMMIT;

GRANT SELECT ON fin.invoices TO fin_mcp_ro;

-- MCP user convenience objects
ALTER SESSION SET CURRENT_SCHEMA = hr_mcp_ro;
CREATE OR REPLACE SYNONYM employees FOR hr.employees;
CREATE OR REPLACE VIEW session_identity AS
SELECT
  SYS_CONTEXT('USERENV', 'SESSION_USER') AS session_user,
  SYS_CONTEXT('CLIENTCONTEXT', 'OAUTH_ISSUER') AS oauth_issuer,
  SYS_CONTEXT('CLIENTCONTEXT', 'OAUTH_PRINCIPAL') AS oauth_principal,
  SYS_CONTEXT('CLIENTCONTEXT', 'OAUTH_APP_ROLES') AS oauth_app_roles,
  SYS_CONTEXT('CLIENTCONTEXT', 'OAUTH_SUB') AS oauth_sub
FROM dual;

ALTER SESSION SET CURRENT_SCHEMA = fin_mcp_ro;
CREATE OR REPLACE SYNONYM invoices FOR fin.invoices;
CREATE OR REPLACE VIEW session_identity AS
SELECT
  SYS_CONTEXT('USERENV', 'SESSION_USER') AS session_user,
  SYS_CONTEXT('CLIENTCONTEXT', 'OAUTH_ISSUER') AS oauth_issuer,
  SYS_CONTEXT('CLIENTCONTEXT', 'OAUTH_PRINCIPAL') AS oauth_principal,
  SYS_CONTEXT('CLIENTCONTEXT', 'OAUTH_APP_ROLES') AS oauth_app_roles,
  SYS_CONTEXT('CLIENTCONTEXT', 'OAUTH_SUB') AS oauth_sub
FROM dual;

ALTER SESSION SET CURRENT_SCHEMA = SYS;
PROMPT Lab schemas ready: HR, FIN, HR_MCP_RO, FIN_MCP_RO
